version: '3.4'

services:
  nasgrad.api:
    build:
      context: .
      dockerfile: NasGrad.API/Dockerfile
      args: 
        APPLICATION_SETTINGS: "appsettings-api.json"
    image: 
      nasgradapi
    ports:
     - "8080:80"
    networks:
     - nasgrad-network

  mongo:
    image: mongo
    ports: 
     - "27017:27017"
    networks:
     - nasgrad-network
  
networks:
  nasgrad-network:
    driver: bridge
