version: '3.4'

services:
  mongo:
    image: mongo
    ports: 
     - "27017:27017"
    volumes:
      - 'mongo:/data/db'

  nasgrad.api:
    depends_on:
      - 'mongo'
    build:
      context: .
      dockerfile: NasGrad.API/Dockerfile
      args: 
        APPLICATION_SETTINGS: "appsettings-api.json"
    image: 
      nasgradapi
    ports:
     - "8080:8080"
    environment:
      - MONGO_URL=mongodb://mongo:27017/app_development

  nasgrad.web:
    build:
      context: .
      dockerfile: NasGrad.Web/Dockerfile
      args: 
        ADDRESS_OF_API: http://${HOST_CURRENT_ADDRESS}:8080 
    image:
      nasgradweb
    ports:
    - "80:80"
    

  
volumes:
  mongo:
