version: '3.4'

services:
  mongo:
    image: mongo
    ports: 
     - "27017:27017"
    volumes:
      - 'mongo:/data/db'
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}

  nasgrad.api:
    depends_on:
      - 'mongo'
    build:
      context: .
      dockerfile: NasGrad.API/Dockerfile
      args: 
        APPLICATION_SETTINGS: "appsettings-api.json"
        MONGODB_USERNAME: ${MONGODB_USERNAME}
        MONGODB_PASSWORD: ${MONGODB_PASSWORD}
    environment:
      ASPNETCORE_URLS: ${ASPNETCORE_URLS}
      ASPNETCORE_Kestrel__Certificates__Default__Password: ${ASPNETCORE_KESTREL_CERTIFICATE_PASSWORD}
      ASPNETCORE_Kestrel__Certificates__Default__Path: ${ASPNETCORE_KESTREL_CERTIFICATE_PATH}
    image: 
      nasgradapi
    ports:     
     - "8081:443"
    volumes:
      - ${CERTIFICATE_PATH}:/root/.dotnet/https

  nasgrad.web:
    build:
      context: .
      dockerfile: NasGrad.Web/Dockerfile
      args: 
        ADDRESS_OF_API: https://${HOST_CURRENT_ADDRESS}:8081 
    image:
      nasgradweb
    ports:
    - "443:443"
    volumes:
      - ${CERTIFICATE_PATH}:/root/.dotnet/https
    environment:
      ASPNETCORE_URLS: ${ASPNETCORE_URLS}
      ASPNETCORE_Kestrel__Certificates__Default__Password: ${ASPNETCORE_KESTREL_CERTIFICATE_PASSWORD}
      ASPNETCORE_Kestrel__Certificates__Default__Path: ${ASPNETCORE_KESTREL_CERTIFICATE_PATH}

volumes:
  mongo:
