version: '3.4'

services:
  mongo:
    image: mongo
    ports: 
     - "27017:27017"
    volumes:
      - 'mongo:/data/db'
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}

  nasgrad.api:
    depends_on:
      - 'mongo'
    build:
      context: .
      dockerfile: NasGrad.API/Dockerfile
      args: 
        APPLICATION_SETTINGS: "appsettings-api.json"
        MONGODB_USERNAME: ${MONGODB_USERNAME}
        MONGODB_PASSWORD: ${MONGODB_PASSWORD}
    image: 
      nasgradapi
    ports:
     - "8080:80"

  nasgrad.web:
    build:
      context: .
      dockerfile: NasGrad.Web/Dockerfile
      args: 
        ADDRESS_OF_API: http://${HOST_CURRENT_ADDRESS}:8080 
    image:
      nasgradweb
    ports:
    - "80:80"
  
volumes:
  mongo:
